# Generated by Django 4.2.10 on 2024-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
